FROM nginx:1.14

RUN apt-get update \
 && apt-get install -y \
    openssl \
    spawn-fcgi \
    fcgiwrap \
    jq \
    curl

COPY auth.sh /etc/nginx/conf.d
COPY default-ssl.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh entrypoint.sh
COPY keys.properties /etc/nginx/conf.d
COPY api.properties /etc/nginx/conf.d
COPY trace.sh /etc/nginx/conf.d
COPY tests.sh /etc/nginx/conf.d
COPY ip-whitelist.conf /etc/nginx/conf.d

RUN chmod +x /etc/nginx/conf.d/auth.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
