version: "3"

services:
  authapi:
    # HTTP authentication API gate
    env_file:
      - api_auth_docker/env.properties
    image: authapi
    ports:
#      - "80:80"
      - "443:443"
    volumes:
      - "~/cyphernode-ssl/certs:/etc/ssl/certs"
      - "~/cyphernode-ssl/private:/etc/ssl/private"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    networks:
      - cyphernodenet

  cyphernode:
    # Bitcoin Mini Proxy
    env_file:
      - proxy_docker/env.properties
    image: btcproxyimg
    volumes:
      # Variable substitutions don't work
      # Match with DB_PATH in proxy_docker/env.properties
      - "~/btcproxydb:/proxy/db"
      # c-lightning looks for $HOME/.lightning/, and $HOME is set to / in the container
      - "~/lndata:/.lightning"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER ./startproxy.sh
    networks:
      - cyphernodenet

  proxycronnode:
    # Async jobs
    env_file:
      - cron_docker/env.properties
    image: proxycronimg
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    networks:
      - cyphernodenet

  pycoinnode:
    # Pycoin
    env_file:
      - pycoin_docker/env.properties
    image: pycoinimg
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER ./startpycoin.sh
    networks:
      - cyphernodenet

  clightningnode:
    # c-lightning lightning network node
    image: clnimg
    ports:
      - "9735:9735"
    volumes:
      - "~/lndata:/.lightning"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER lightningd
    networks:
      - cyphernodenet

  btcnode:
    # Bitcoin node
    image: btcnode
#    ports:
#      - "18333:18333"
#      - "29000:29000"
#      - "8333:8333"
    volumes:
      - "~/btcdata:/.bitcoin"
    command: $USER bitcoind
    networks:
      - cyphernodenet

networks:
  cyphernodenet:
    external: true
