version: "3"

services:
  gatekeeper:
    # HTTP authentication API gate
    env_file:
      - api_auth_docker/env.properties
    image: cyphernode/gatekeeper:cyphernode-0.05
    ports:
#      - "80:80"
      - "443:443"
    volumes:
      - "~/cyphernode-ssl/certs:/etc/ssl/certs"
      - "~/cyphernode-ssl/private:/etc/ssl/private"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    networks:
      - cyphernodenet

  proxy:
    # Bitcoin Mini Proxy
    env_file:
      - proxy_docker/env.properties
    image: cyphernode/proxy:cyphernode-0.05
    volumes:
      # Variable substitutions don't work
      # Match with DB_PATH in proxy_docker/env.properties
      - "~/btcproxydb:/proxy/db"
      # c-lightning looks for $HOME/.lightning/, and $HOME is set to / in the container
      - "~/lndata:/.lightning"
      # OTS files, shared with otsclient container
      - "~/otsfiles:/otsfiles"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER ./startproxy.sh
    networks:
      - cyphernodenet

  proxycron:
    # Async jobs
    env_file:
      - cron_docker/env.properties
    image: cyphernode/proxycron:cyphernode-0.05
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    networks:
      - cyphernodenet

  pycoin:
    # Pycoin
    env_file:
      - pycoin_docker/env.properties
    image: cyphernode/pycoin:cyphernode-0.05
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER ./startpycoin.sh
    networks:
      - cyphernodenet

  otsclient:
    # otsclient JS
    env_file:
      - otsclient_docker/env.properties
    image: cyphernode/ots:cyphernode-0.05
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    volumes:
      - "~/otsfiles:/otsfiles"
    command: $USER /script/startotsclient.sh
    networks:
      - cyphernodenet

  lightning:
    # c-lightning lightning network node
    image: cyphernode/clightning:dev
    ports:
      - "9735:9735"
    volumes:
      - "~/lndata:/.lightning"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER lightningd
    networks:
      - cyphernodenet

  bitcoin:
    # Bitcoin node
    image: cyphernode/bitcoin:0.17.0
#    ports:
#      - "18333:18333"
#      - "29000:29000"
#      - "8333:8333"
    volumes:
      - "~/btcdata:/.bitcoin"
    command: $USER bitcoind
    networks:
      - cyphernodenet

networks:
  cyphernodenet:
    external: true
